### ISSUE TITLE
太谦虚了

### ISSUE THREAD

**Issue by feitas** [mousheng/tooljet_cn#2]
做了这么多，还说自己精力和能力有限，太谦虚了，哈哈

你这花了不少时间吧？

**Comment by mousheng** [comment]
非常多，这段话主要还是因为兼容性问题，很多功能改了之后会不兼容，轻则组件无法显示，需要删除原组件重新添加，重则创建的APP页面会直接崩，要重新创建

**Comment by feitas** [comment]
我现在还停留在搞成https的问题上，晕了
