### ISSUE TITLE
[docs]: 

### ISSUE THREAD

**Issue by Daqiv** [mousheng/tooljet_cn#3]
### Summary

你好,大神,弱弱的问下您.官方的文档 https://docs.tooljet.com/docs/setup/client/ 这里的意思是前后端分离吗? 那么Deploy static assets的意思是这个项目支持导出静态资源么?

### Issue Type

Documentation bug

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by mousheng** [comment]
tooljet是前后端分离的，.env设置可以设置serverhost，根据文档，应该可以多个前端连接后端，做均衡负载，当然这个功能我也没试验过
